import { generateOpenRouterChat } from "@/lib/ai/openrouter-client";
import { parseJsonObjectFromLlm } from "@/lib/ai/json-extract";
import type { AiAssistantIntent } from "./contracts";
export type OrchestratorInput = { message: string; turns: unknown[]; artifact: unknown | null };
export type GroundedOrchestratorInput = OrchestratorInput & { context?: string };
export type OrchestratorOutput = { message: string; intent: AiAssistantIntent; kind?: "narrative" | "wiki"; title?: string; content?: string; patch?: { path: string; value: string }; actionName?: string; actionInput?: Record<string, unknown> };
export type AssistantModelRouter = { orchestrate(input: GroundedOrchestratorInput): Promise<OrchestratorOutput> };
const intents = new Set<AiAssistantIntent>(["answer","create","revise","generate_image","save","discard","ask_clarification"]);
const text = (v: unknown, fallback = "") => typeof v === "string" ? v.trim() || fallback : fallback;
const obj = (v: unknown) => v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : {};
function prompt(input: GroundedOrchestratorInput) { const active = obj(input.artifact); const history = (input.turns as Array<{role?:unknown;content?:unknown}>).slice(-8).map(t => `${t.role === "assistant" ? "Assistente" : "GM"}: ${text(t.content)}`).join("\n"); return `Sei l'Assistente GM di Barber & Dragons. Genera testo italiano utile e creativo centrato ESCLUSIVAMENTE sul soggetto richiesto, non un riassunto dell'ambientazione. Non ripetere la richiesta del GM. Usa al massimo DUE fatti dalle FONTI e solo se servono direttamente al soggetto; non forzare nomi, luoghi o fazioni irrilevanti. I dettagli del soggetto non presenti nelle fonti sono proposte creative e non vanno citati. Se citi un fatto canonico, usa [E#] solo alla fine della frase pertinente: massimo due citazioni nell'intero testo. Per modifiche, conserva integralmente la bozza attiva e cambia SOLO i campi richiesti. Non salvare nulla automaticamente. Nel campo message rispondi come un assistente conversazionale: indica in modo sintetico cosa hai applicato e cosa non hai potuto applicare con il motivo. Non incollare mai l'intero testo narrativo nel message: quel testo va solo nel campo content/artefatto.

Per una voce Wiki restituisci kind="wiki", actionName="wiki.entity.create" (o wiki.entity.update solo quando entityId esiste) e actionInput. actionInput deve contenere: type (npc|location|item|monster|lore), title, content, visibility (public|secret|selective), attributes, tags, audiences {userIds,partyIds}, relations [{targetType:"wiki"|"map",targetId,label}], imageUrl (o null), sortOrder (o null), isCore, includeInCampaignAiMemory, linkedMissionId (o null), xpValue. Attributi: NPC race,class,age,statblock,relationships,loot; location loot; monster combat_stats {hp,ac,cr,attacks}, statblock, loot; lore is_chapter,summary; item {}. gm_notes è sempre in attributes. Compila tutto con stringhe vuote/null/[] quando non applicabile. Statblock, HP, AC, GS, PE e attacchi possono essere compilati SOLO quando una fonte regolistica ufficiale è fornita nelle FONTI; cita la fonte nel message. In assenza lascia i relativi campi vuoti e xpValue 0, senza inventare statistiche, e rifiuta esplicitamente quella sola modifica nel message. Per revisioni di una Wiki restituisci in actionInput soltanto i campi modificati: il server conserva gli altri con un deep merge. linkedMissionId deve essere solo un UUID fornito dal server nelle FONTI, mai un ID inventato.

Rispondi SOLO JSON: {"intent":"create|revise|generate_image|save|answer|ask_clarification","message":"breve riepilogo della modifica","title":"...","content":"bozza completa","kind":"narrative|wiki","actionName":"...","actionInput":{...}}. Per nuova storia usa create e content completo; per modifica usa revise e content completo sostitutivo; per immagini generate_image con descrizione visiva. FONTI:\n${input.context || "Nessuna fonte canonica recuperata."}\nBOZZA ATTIVA:\n${active.id ? JSON.stringify(active.payload) : "nessuna"}\nCRONOLOGIA:\n${history}\nRICHIESTA GM:\n${input.message}`; }
export const openRouterAssistantRouter: AssistantModelRouter = { async orchestrate(input) { const parsed = parseJsonObjectFromLlm(await generateOpenRouterChat(prompt(input), { temperature: 0.55, maxTokens: 3000, jsonMode: true })); if (!parsed.ok) throw new Error("Il modello ha restituito un formato non valido."); const out = parsed.value; const intent = text(out.intent) as AiAssistantIntent; if (!intents.has(intent)) throw new Error("Intent non consentito."); const content = text(out.content); if ((intent === "create" || intent === "generate_image" || intent === "revise") && !content) throw new Error("Il modello non ha generato contenuto."); const isWiki = out.kind === "wiki"; const requestedAction = text(out.actionName); const activeInput = obj(obj(input.artifact).payload).actionInput; const activeEntityId = obj(activeInput).entityId; const actionName = requestedAction === "wiki.entity.create" || requestedAction === "wiki.entity.update" ? requestedAction : isWiki ? (typeof activeEntityId === "string" && activeEntityId ? "wiki.entity.update" : "wiki.entity.create") : ""; return { message: text(out.message, "Ho preparato una proposta revisionabile."), intent, kind: isWiki ? "wiki" : "narrative", title: text(out.title, "Bozza Assistente GM"), content, ...(intent === "revise" ? { patch: { path: "/content", value: content } } : {}), ...(actionName ? { actionName, actionInput: obj(out.actionInput) } : {}) }; } };
/** Double locale: non usare nel runtime. */
export const deterministicRouter: AssistantModelRouter = { async orchestrate({ message, artifact }) { const m = message.trim(); if (!m) return { message: "Quale richiesta vuoi affidarmi?", intent: "ask_clarification" }; if (/\b(salva|conferma)\b/i.test(m)) return { message: "La bozza è pronta per la conferma UI.", intent: "save" }; if (artifact) return { message: "Ho aggiornato la bozza.", intent: "revise", patch: { path: "/content", value: `${(artifact as { payload?: { content?: string } }).payload?.content ?? ""}\n\n${m}` } }; return { message: "Ho preparato una bozza narrativa revisionabile.", intent: "create", title: m, content: m }; } };
