import { generateOpenRouterChat } from "@/lib/ai/openrouter-client";
import { parseJsonObjectFromLlm } from "@/lib/ai/json-extract";
import type { AiAssistantIntent } from "./contracts";
export type OrchestratorInput = { message: string; turns: unknown[]; artifact: unknown | null };
export type GroundedOrchestratorInput = OrchestratorInput & { context?: string };
export type OrchestratorOutput = { message: string; intent: AiAssistantIntent; kind?: "narrative" | "wiki"; title?: string; content?: string; patch?: { path: string; value: string }; actionName?: string; actionInput?: Record<string, unknown> };
export type AssistantModelRouter = { orchestrate(input: GroundedOrchestratorInput): Promise<OrchestratorOutput> };
const intents = new Set<AiAssistantIntent>(["answer","create","revise","generate_image","save","discard","ask_clarification"]);
const text = (v: unknown, fallback = "") => typeof v === "string" ? v.trim() || fallback : fallback;
const obj = (v: unknown) => v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, unknown> : {};
function prompt(input: GroundedOrchestratorInput) { const active = obj(input.artifact); const history = (input.turns as Array<{role?:unknown;content?:unknown}>).slice(-8).map(t => `${t.role === "assistant" ? "Assistente" : "GM"}: ${text(t.content)}`).join("\n"); return `Sei l'Assistente GM di Barber & Dragons. Genera testo italiano utile e creativo, non ripetere la richiesta del GM. Usa come fatti solo le FONTI; ogni aggiunta non presente è proposta creativa. Per fatti canonici cita [E#]. Non salvare nulla automaticamente. Rispondi SOLO JSON: {"intent":"create|revise|generate_image|save|answer|ask_clarification","message":"...","title":"...","content":"bozza completa","kind":"narrative|wiki"}. Per nuova storia usa create e content completo; per modifica usa revise e content completo sostitutivo; per immagini generate_image con descrizione visiva. FONTI:\n${input.context || "Nessuna fonte canonica recuperata."}\nBOZZA ATTIVA:\n${active.id ? JSON.stringify(active.payload) : "nessuna"}\nCRONOLOGIA:\n${history}\nRICHIESTA GM:\n${input.message}`; }
export const openRouterAssistantRouter: AssistantModelRouter = { async orchestrate(input) { const parsed = parseJsonObjectFromLlm(await generateOpenRouterChat(prompt(input), { temperature: 0.55, maxTokens: 2400, jsonMode: true })); if (!parsed.ok) throw new Error("Il modello ha restituito un formato non valido."); const out = parsed.value; const intent = text(out.intent) as AiAssistantIntent; if (!intents.has(intent)) throw new Error("Intent non consentito."); const content = text(out.content); if ((intent === "create" || intent === "generate_image" || intent === "revise") && !content) throw new Error("Il modello non ha generato contenuto."); return { message: text(out.message, "Ho preparato una proposta revisionabile."), intent, kind: out.kind === "wiki" ? "wiki" : "narrative", title: text(out.title, "Bozza Assistente GM"), content, ...(intent === "revise" ? { patch: { path: "/content", value: content } } : {}) }; } };
/** Double locale: non usare nel runtime. */
export const deterministicRouter: AssistantModelRouter = { async orchestrate({ message, artifact }) { const m = message.trim(); if (!m) return { message: "Quale richiesta vuoi affidarmi?", intent: "ask_clarification" }; if (/\b(salva|conferma)\b/i.test(m)) return { message: "La bozza è pronta per la conferma UI.", intent: "save" }; if (artifact) return { message: "Ho aggiornato la bozza.", intent: "revise", patch: { path: "/content", value: `${(artifact as { payload?: { content?: string } }).payload?.content ?? ""}\n\n${m}` } }; return { message: "Ho preparato una bozza narrativa revisionabile.", intent: "create", title: m, content: m }; } };
