"use server";
import { createSupabaseServerClient } from "@/utils/supabase/server";
import { getTenantAdapter } from "@/modules/command-center/adapters";
import { openRouterAssistantRouter } from "../ai-v2/assistant-model-router";
import { SupabaseThreadRepository } from "../ai-v2/thread-repository";
import { runAssistantTurn } from "../ai-v2/orchestrator";
import { createSupabaseAdminClient } from "@/utils/supabase/admin";
import { loadAssistantContext } from "../ai-v2/context-service";
import { groundedNarrativeInstruction } from "../ai-v2/narrative-service";
import { previewAssistantArtifactSave, saveAssistantArtifact } from "../ai-v2/save-service";
import { actionForArtifact } from "../ai-v2/action-bridge";
import { generateAssistantImage } from "../ai-v2/image-service";
import { checkAiAssistantV2PilotAccess } from "../ai-v2/access";
async function authorizeCampaign(supabase: any, campaignId: string | null, role: string) { if (role === "admin") return true; if (!campaignId) return false; const { data, error } = await supabase.rpc("can_manage_campaign_as_gm", { p_campaign_id: campaignId }); return !error && data === true; }
async function auth() { const supabase = await createSupabaseServerClient(); const access = await getTenantAdapter().assertCanAccessCommandCenter(supabase); return { supabase, access }; }
async function authorizePilotCampaign(
  supabase: any,
  input: { userId: string; role: "gm" | "admin"; campaignId: string | null }
) {
  if (!input.campaignId || !(await authorizeCampaign(supabase, input.campaignId, input.role))) {
    return { ok: false as const, error: "Non sei autorizzato a gestire questa campagna." };
  }
  return checkAiAssistantV2PilotAccess(createSupabaseAdminClient(), input);
}
export async function runAiAssistantV2Turn(input: { campaignId?: string | null; message: string; threadId?: string }) { const { supabase, access } = await auth(); if (!access.ok) return { success: false as const, error: access.error }; const campaignId = input.campaignId ?? null; const authorized = await authorizePilotCampaign(supabase, { userId: access.ctx.userId, role: access.ctx.role, campaignId }); if (!authorized.ok) return { success: false as const, error: authorized.error }; if (!input.message.trim()) return { success: false as const, error: "Il messaggio non può essere vuoto." }; try { const admin = createSupabaseAdminClient(); const context = await loadAssistantContext(admin, campaignId, input.message); const result = await runAssistantTurn({ repo: new SupabaseThreadRepository(admin), router: openRouterAssistantRouter, ownerUserId: access.ctx.userId, campaignId, message: input.message, threadId: input.threadId, context: groundedNarrativeInstruction(context) }); return { success: true as const, data: { ...result, evidence: context?.result.sources ?? result.evidence } }; } catch (error) { console.error("[runAiAssistantV2Turn]", error); return { success: false as const, error: "Non è stato possibile completare il turno. La bozza precedente è rimasta invariata." }; } }
export async function confirmAiAssistantV2Save(input: { artifactId: string; revision: number; actionName: string }) { const { supabase, access } = await auth(); if (!access.ok) return { success: false as const, error: access.error }; try { const admin = createSupabaseAdminClient(); const repo = new SupabaseThreadRepository(admin); const artifact = await repo.getArtifact(input.artifactId); if (!artifact) return { success: false as const, error: "Artefatto non autorizzato." }; const authorized = await authorizePilotCampaign(supabase, { userId: access.ctx.userId, role: access.ctx.role, campaignId: artifact.campaignId }); if (!authorized.ok) return { success: false as const, error: authorized.error }; const saved = await saveAssistantArtifact(admin, artifact, input.revision, input.actionName); return { success: true as const, data: saved }; } catch (error) { console.error("[confirmAiAssistantV2Save]", error); return { success: false as const, error: error instanceof Error ? error.message : "Salvataggio non riuscito." }; } }
export async function prepareAiAssistantV2Save(input: { artifactId: string; revision: number }) { const { supabase, access } = await auth(); if (!access.ok) return { success: false as const, error: access.error }; try { const artifact = await new SupabaseThreadRepository(createSupabaseAdminClient()).getArtifact(input.artifactId); if (!artifact || artifact.revision !== input.revision) return { success: false as const, error: "Artefatto non autorizzato o non aggiornato." }; const authorized = await authorizePilotCampaign(supabase, { userId: access.ctx.userId, role: access.ctx.role, campaignId: artifact.campaignId }); if (!authorized.ok) return { success: false as const, error: authorized.error }; return { success: true as const, data: await previewAssistantArtifactSave(artifact, actionForArtifact(artifact)) }; } catch (error) { return { success: false as const, error: error instanceof Error ? error.message : "Anteprima non disponibile." }; } }
export async function reviseAiAssistantV2Artifact(input: { artifactId: string; revision: number; content: string }) { const { supabase, access } = await auth(); if (!access.ok) return { success: false as const, error: access.error }; try { const repo = new SupabaseThreadRepository(createSupabaseAdminClient()); const artifact = await repo.getArtifact(input.artifactId); if (!artifact || artifact.revision !== input.revision) return { success: false as const, error: "Bozza non autorizzata o già aggiornata." }; const authorized = await authorizePilotCampaign(supabase, { userId: access.ctx.userId, role: access.ctx.role, campaignId: artifact.campaignId }); if (!authorized.ok) return { success: false as const, error: authorized.error }; const updated = await repo.createRevision(artifact, { status: "draft", payload: { ...artifact.payload, content: input.content } }); return { success: true as const, data: updated }; } catch (error) { return { success: false as const, error: error instanceof Error ? error.message : "Modifica non salvata." }; } }
export async function generateAiAssistantV2Image(input: { campaignId: string; description: string; artifactId: string }) { const { supabase, access } = await auth(); if (!access.ok) return { success: false as const, error: access.error }; const authorized = await authorizePilotCampaign(supabase, { userId: access.ctx.userId, role: access.ctx.role, campaignId: input.campaignId }); if (!authorized.ok) return { success: false as const, error: authorized.error }; try { const admin = createSupabaseAdminClient(); const repo = new SupabaseThreadRepository(admin); const previous = await repo.getArtifact(input.artifactId); if (!previous || previous.campaignId !== input.campaignId) return { success: false as const, error: "Bozza immagine non trovata." }; const generated = await generateAssistantImage(admin, { campaignId: input.campaignId, description: input.description, entityType: "npc", entityTitle: String(previous.payload.title ?? ""), previousImageUrl: typeof previous.payload.imageUrl === "string" ? previous.payload.imageUrl : null, sourceRefs: previous.sourceRefs }); const updated = await repo.createRevision(previous, { kind: "image", status: "draft", payload: { ...previous.payload, imageUrl: generated.imageUrl }, sourceRefs: generated.sources as never[], policyVersion: `${generated.policyVersion}:${generated.policyHash}` }); return { success: true as const, data: updated }; } catch (error) { console.error("[generateAiAssistantV2Image]", error); return { success: false as const, error: error instanceof Error ? error.message : "Generazione immagine non riuscita." }; } }
