-- Allow mission plans generated by the GM assistant without changing existing kinds or access policies.
ALTER TABLE public.ai_assistant_artifacts
  DROP CONSTRAINT ai_assistant_artifacts_kind_check;
ALTER TABLE public.ai_assistant_artifacts
  ADD CONSTRAINT ai_assistant_artifacts_kind_check
  CHECK (kind IN ('narrative', 'wiki', 'image', 'rules', 'sheet', 'action', 'mission_plan'));
