"use client";
import { useState, useTransition } from "react";
import { Send, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { confirmAiAssistantV2Save, generateAiAssistantV2Image, prepareAiAssistantV2Save, reviseAiAssistantV2Artifact, runAiAssistantV2Turn } from "@/modules/command-center/server/ai-v2-actions";
import type { AiAssistantArtifact, AiAssistantSourceRef } from "@/modules/command-center/ai-v2/contracts";
import { AiAssistantV2ArtifactCard } from "./ai-assistant-v2-artifact-card";
import { AiAssistantV2Sources } from "./ai-assistant-v2-sources";
type Message = { role: "user" | "assistant"; content: string };
export function AiAssistantV2Panel({ campaignId }: { campaignId: string | null }) {
  const [input, setInput] = useState(""); const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "Sono l'Assistente v2. Posso preparare bozze revisionabili per la campagna selezionata." }]); const [artifact, setArtifact] = useState<AiAssistantArtifact | null>(null); const [sources, setSources] = useState<AiAssistantSourceRef[]>([]); const [preparedAction, setPreparedAction] = useState<string | null>(null); const [isPending, startTransition] = useTransition();
  function send(message = input) { const value = message.trim(); if (!value || isPending) return; setInput(""); setPreparedAction(null); setMessages((m) => [...m, { role: "user", content: value }]); startTransition(async () => { const res = await runAiAssistantV2Turn({ campaignId, message: value }); if (!res.success) { toast.error(res.error); return; } let next = res.data.artifact; if (next?.kind === "image" && campaignId) { const image = await generateAiAssistantV2Image({ campaignId, artifactId: next.id }); if (!image.success) toast.error(image.error); else next = image.data; } const reply = next && typeof next.payload.content === "string" ? next.payload.content : res.data.assistantMessage; setMessages((m) => [...m, { role: "assistant", content: reply }]); if (next) setArtifact(next); setSources(res.data.evidence.filter((source) => reply.includes(`[${source.evidenceId}]`))); }); }
  function prepareSave() { if (!artifact) return; startTransition(async () => { const content = String(artifact.payload.content ?? ""); const persisted = await reviseAiAssistantV2Artifact({ artifactId: artifact.id, revision: artifact.revision, content }); if (!persisted.success) { toast.error(persisted.error); return; } setArtifact(persisted.data); const res = await prepareAiAssistantV2Save({ artifactId: persisted.data.id, revision: persisted.data.revision }); if (!res.success) { toast.error(res.error); return; } setPreparedAction(res.data.actionName); toast.success("Anteprima pronta: conferma per salvare nella campagna"); }); }
  function confirmSave() { if (!artifact || !preparedAction) return; startTransition(async () => { const res = await confirmAiAssistantV2Save({ artifactId: artifact.id, revision: artifact.revision, actionName: preparedAction }); if (!res.success) { toast.error(res.error); return; } setArtifact({ ...artifact, status: "saved", savedEntity: res.data }); toast.success("Artefatto salvato nella campagna"); }); }
  return <div className="flex h-full min-h-0 flex-col bg-gradient-to-br from-[#17131a] via-[#100e14] to-[#0b0a10]"><div className="flex shrink-0 items-center justify-between border-b border-white/[0.07] px-5 py-3"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-barber-gold" /><div><p className="text-sm font-medium text-barber-paper">Assistente v2</p><p className="text-[11px] text-barber-paper/45">Conversazione contestuale · nessuna scrittura automatica</p></div></div><span className="rounded-full border border-barber-gold/25 px-2 py-1 text-[10px] uppercase tracking-wider text-barber-gold">{campaignId ? "Campagna attiva" : "Seleziona campagna"}</span></div><div className="grid min-h-0 flex-1 gap-4 overflow-y-auto p-4 lg:grid-cols-[minmax(0,1fr)_minmax(300px,420px)] lg:p-5"><div className="flex min-h-[420px] flex-col rounded-2xl border border-white/[0.07] bg-black/10 p-4"><div className="min-h-0 flex-1 space-y-3 overflow-y-auto" aria-live="polite">{messages.map((m, i) => <div key={`${m.role}-${i}`} className={m.role === "user" ? "ml-auto max-w-[85%] rounded-2xl rounded-br-sm bg-barber-gold/15 px-3 py-2 text-sm text-barber-paper" : "max-w-[90%] rounded-2xl rounded-bl-sm border border-white/[0.07] bg-white/[0.035] px-3 py-2 text-sm leading-6 text-barber-paper/80"}>{m.content}</div>)}</div><div className="mt-4 flex gap-2"><Textarea value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); } }} placeholder="Scrivi una richiesta naturale…" className="min-h-12 resize-none border-white/10 bg-barber-dark/70" disabled={isPending} /><Button onClick={() => send()} disabled={isPending || !input.trim()} className="self-end"><Send className="h-4 w-4" /></Button></div></div><div className="space-y-4">{artifact ? <AiAssistantV2ArtifactCard artifact={artifact} prepared={Boolean(preparedAction)} onEdit={(content) => { setPreparedAction(null); setArtifact({ ...artifact, payload: { ...artifact.payload, content } }); }} onRegenerate={() => send("Rigenera questa bozza mantenendo il contesto")} onDiscard={() => { setPreparedAction(null); setArtifact(null); toast.message("Bozza scartata"); }} onPrepare={prepareSave} onConfirm={confirmSave} /> : <div className="rounded-2xl border border-dashed border-white/10 p-5 text-sm text-barber-paper/45">La bozza apparirà qui dopo la prima richiesta.</div>}<AiAssistantV2Sources sources={sources} /></div></div></div>;
}
